/**
 * Action Handler System
 *
 * Handles interactive actions triggered by dynamic components.
 * All actions are serializable (no functions) and can be generated by the LLM.
 *
 * Updated to support local actions for <100ms feedback:
 * - expand_card: Uses event bus instead of API calls
 * - add_entity: Integrates with command history for undo/redo
 */

import {
  Action,
  ComponentSpec,
  isAction,
  FetchDataAction,
  RefineQueryAction,
  ExpandCardAction,
  AddEntityAction,
  OpenUrlAction
} from '@/types/api';
import { bus } from './eventBus';
import { run } from './commandHistory';

// Toast notification type (compatible with shadcn/ui toast)
type ToastFunction = (options: {
  title: string;
  description?: string;
  variant?: 'default' | 'destructive';
}) => void;

/**
 * ActionHandler Configuration
 */
interface ActionHandlerConfig {
  setComponents: React.Dispatch<React.SetStateAction<ComponentSpec[]>>;
  setLoading: React.Dispatch<React.SetStateAction<boolean>>;
  toast: ToastFunction;
  apiClient?: any; // Optional API client for fetch operations
}

/**
 * ActionHandler Class
 * 
 * Centralized handler for all interactive actions in the UI.
 * Supports async operations, error handling, and optimistic updates.
 */
export class ActionHandler {
  private setComponents: React.Dispatch<React.SetStateAction<ComponentSpec[]>>;
  private setLoading: React.Dispatch<React.SetStateAction<boolean>>;
  private toast: ToastFunction;
  private apiClient?: any;

  constructor(config: ActionHandlerConfig) {
    this.setComponents = config.setComponents;
    this.setLoading = config.setLoading;
    this.toast = config.toast;
    this.apiClient = config.apiClient;
  }

  /**
   * Main handler - Routes actions to specific handlers
   */
  async handle(action: Action): Promise<void> {
    console.log('[ActionHandler] Handling action:', action);

    try {
      switch (action.type) {
        case 'fetch_data':
          await this.handleFetchData(action as FetchDataAction);
          break;
        case 'refine_query':
          await this.handleRefineQuery(action as RefineQueryAction);
          break;
        case 'expand_card':
          await this.handleExpandCard(action as ExpandCardAction);
          break;
        case 'add_entity':
          await this.handleAddEntity(action as AddEntityAction);
          break;
        case 'open_url':
          await this.handleOpenUrl(action as OpenUrlAction);
          break;
        default:
          console.warn('[ActionHandler] Unknown action type:', (action as any).type);
          this.toast({
            title: 'Unknown Action',
            description: `Action type "${(action as any).type}" is not supported`,
            variant: 'destructive',
          });
      }
    } catch (error) {
      console.error('[ActionHandler] Error handling action:', error);
      this.toast({
        title: 'Action Failed',
        description: error instanceof Error ? error.message : 'An unknown error occurred',
        variant: 'destructive',
      });
    }
  }

  /**
   * Fetch Data Action - Retrieve data from external sources
   */
  private async handleFetchData(action: FetchDataAction): Promise<void> {
    const { source, ticker, url, query } = action.params;
    
    console.log('[ActionHandler] Fetching data:', action.params);
    
    this.setLoading(true);
    
    try {
      this.toast({
        title: 'Fetching Data',
        description: `Loading ${source} data...`,
      });

      // Simulate API call (replace with actual API client)
      await new Promise(resolve => setTimeout(resolve, 1500));

      // TODO: Replace with actual data fetching logic
      // Example: const data = await this.apiClient.fetchData(source, { ticker, url, query });

      // For now, add a placeholder component
      const newComponent: ComponentSpec = {
        type: 'metric_card',
        props: {
          label: `${source} Data`,
          value: ticker || 'Loaded',
          sublabel: 'Data successfully retrieved',
        },
        key: `fetched-${Date.now()}`,
      };

      // Append new component (optimistic update)
      this.setComponents((prev) => [...prev, newComponent]);

      this.toast({
        title: 'Data Loaded',
        description: `Successfully fetched ${source} data`,
      });
    } catch (error) {
      console.error('[ActionHandler] Fetch data error:', error);
      throw error;
    } finally {
      this.setLoading(false);
    }
  }

  /**
   * Refine Query Action - Trigger new UI generation with refined query
   */
  private async handleRefineQuery(action: RefineQueryAction): Promise<void> {
    const { query } = action.params;
    
    console.log('[ActionHandler] Refining query:', query);
    
    this.setLoading(true);
    
    try {
      this.toast({
        title: 'Refining Query',
        description: 'Generating updated UI...',
      });

      // Call the refine/create endpoint with the new query
      const response = await fetch('http://localhost:8000/api/refine/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ input: query }),
      });

      if (!response.ok) {
        throw new Error(`Failed to refine query: ${response.statusText}`);
      }

      const data = await response.json();
      
      if (data.success && data.components && data.components.length > 0) {
        console.log('[ActionHandler] Received new components:', data.components.length);
        // Append new components to existing ones
        this.setComponents((prev) => [...prev, ...data.components]);

        this.toast({
          title: 'Query Refined',
          description: 'UI has been updated',
        });
      } else {
        throw new Error('No components returned from refinement');
      }
    } catch (error) {
      console.error('[ActionHandler] Refine query error:', error);
      this.toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Failed to refine query',
        variant: 'destructive',
      });
      throw error;
    } finally {
      this.setLoading(false);
    }
  }

  /**
   * Expand Card Action - Show detailed view of an entity (LOCAL <100ms)
   *
   * This is now a LOCAL action - no API call required!
   * Emits event for card to handle expansion inline.
   */
  private async handleExpandCard(action: ExpandCardAction): Promise<void> {
    const { entityId } = action.params;

    console.log('[ActionHandler] Expanding card (local):', entityId);

    // Emit event for card to handle expansion locally
    // This enables <100ms response instead of waiting for LLM
    bus.emit('CARD_EXPAND_REQUESTED', { entityId });

    // No toast needed - the card will expand instantly
    console.log('[ActionHandler] Card expand event emitted for:', entityId);
  }

  /**
   * Add Entity Action - Add new entity/component to the UI (with UNDO support)
   */
  private async handleAddEntity(action: AddEntityAction): Promise<void> {
    const { template, data } = action.params;

    console.log('[ActionHandler] Adding entity:', template, data);

    this.setLoading(true);

    try {
      // Create component based on template
      const newComponent: ComponentSpec = {
        type: template === 'competitor' ? 'metric_card' : 'text',
        props: data || {
          label: 'New Entity',
          value: template,
        },
        key: `added-${Date.now()}`,
      };

      // Add to UI with undo/redo support via command history
      run({
        label: `Add ${template}`,
        do: () => {
          this.setComponents((prev) => [...prev, newComponent]);
          bus.emit('ENTITY_ADDED', { template, data });
        },
        undo: () => {
          this.setComponents((prev) => prev.filter(c => c.key !== newComponent.key));
          bus.emit('ENTITY_REMOVED', { key: newComponent.key });
        },
      });

      this.toast({
        title: 'Entity Added',
        description: `Added new ${template}`,
      });
    } catch (error) {
      console.error('[ActionHandler] Add entity error:', error);
      throw error;
    } finally {
      this.setLoading(false);
    }
  }

  /**
   * Open URL Action - Open external link safely
   */
  private async handleOpenUrl(action: OpenUrlAction): Promise<void> {
    const { url } = action.params;
    
    console.log('[ActionHandler] Opening URL:', url);
    
    try {
      // Validate URL
      const validUrl = new URL(url);
      
      // Open in new tab with security flags
      window.open(
        validUrl.href,
        '_blank',
        'noopener,noreferrer'
      );

      this.toast({
        title: 'Opening Link',
        description: 'Opening in new tab...',
      });
    } catch (error) {
      console.error('[ActionHandler] Invalid URL:', error);
      this.toast({
        title: 'Invalid URL',
        description: 'The provided URL is not valid',
        variant: 'destructive',
      });
    }
  }
}

/**
 * Export action types for convenience
 */
export type { Action };
export { isAction };
